### ISSUE TITLE
Fails to start on Wayland (even on XWayland)

### ISSUE THREAD

**Issue by maxice8** [flathub/com.jagex.RuneScape#120] opened 2020-04-17 08:52 UTC
Trying on Swaywm with XWayland starts the first window.
![image](https://user-images.githubusercontent.com/30738253/79550931-60ae9200-806f-11ea-838a-ed610eb9d081.png)

Then it closes 

![image](https://user-images.githubusercontent.com/30738253/79550957-699f6380-806f-11ea-9a89-d1f9b89314d9.png)

I can run the game on Xorg with Fluxbox

**Comment by Garbee** [comment] 2020-04-17 17:27
Can you even run the game client directly on Wayland? AFAIK Jagex only supports Xorg.

**Comment by maxice8** [comment] 2020-04-17 17:34
I expected it to be like Steam and it starting in XWayland mode

**Comment by Garbee** [comment] 2020-04-17 20:57
That doesn't answer anything.

Can you run the Jagex provided game client directly without any wrappers?

**Comment by Garbee** [comment] 2020-04-19 17:51
I just tested on Ubuntu 19.04 running from Wayland. The game client and flatpak wrapped version both ran perfectly fine. So there seems to be something specific to your setup going on that is causing the problem.

Perhaps there is something with the window manager causing an incompatibility because Jagex hasn't built for it. Or something else with whatever Linux distro you are using that is triggering the failure.

Since we don't have any real information here to build a reproducible case from, I'm closing this issue out since there doesn't seem to be anything we can do within the flatpak wrapper to resolve this situation.

**Closed by Garbee** 2020-04-19 17:51 UTC

**Comment by Sukid** [comment] 2020-12-16 21:37
Just to note from my own testing, the game actually WILL try to start natively in Wayland. I do have SDL_VIDEODRIVER=wayland set globally when I use Sway, so I'm not sure if it does this automatically, but it does try. However, in my particular case it never makes it past "loading application resources" when I do this. I need to run it with SDL_VIDEODRIVER=x11 to make it launch with xwayland, after which it works fine. This has nothing to do with the flatpak though, just thought I would mention it because I haven't seen this anywhere.
