### ISSUE TITLE
Wrong size of extra data

### ISSUE THREAD

**Issue by bunatl** [flathub/com.jagex.RuneScape#113] opened 2020-03-25 14:28 UTC
Hey guys, I tried to install your launcher however it didn't go through.

$ sudo flatpak install 'flathub' 'com.jagex.RuneScape'
Installing in system:
com.jagex.RuneScape/x86_64/stable flathub 0fe69d9d6bf6
  permissions: ipc, network, pulseaudio, x11, devices
  tags: proprietary
Is this ok [y/n]: y
Installing: com.jagex.RuneScape/x86_64/stable from flathub
[####################] Downloading files: 1/1 96,5 kB           
error: Failed to install com.jagex.RuneScape/x86_64/stable: Wrong size for extra data https://content.runescape.com/downloads/ubuntu/pool/non-free/r/runescape-launcher/runescape-launcher_2.2.6_amd64.deb

PC setup:
System:    Host: mintVB Kernel: 4.15.0-20-generic x86_64 bits: 64 compiler: gcc v: 7.3.0 
           Desktop: Cinnamon 4.0.10 wm: muffin dm: LightDM Distro: Linux Mint 19.1 Tessa 
           base: Ubuntu 18.04 bionic 
Machine:   Type: Virtualbox System: innotek product: VirtualBox v: 1.2 serial: <filter> 
           Chassis: Oracle Corporation type: 1 serial: <filter> 
           Mobo: Oracle model: VirtualBox v: 1.2 serial: <filter> BIOS: innotek v: VirtualBox 
           date: 12/01/2006 
CPU:       Topology: Triple Core model: AMD Phenom II X4 965 bits: 64 type: MCP arch: K10 rev: 3 
           L2 cache: 1536 KiB 
           flags: lm nx pae sse sse2 sse3 sse4a bogomips: 20468 
           Speed: 3411 MHz min/max: N/A Core speeds (MHz): 1: 3411 2: 3411 3: 3411 
Graphics:  Device-1: VMware SVGA II Adapter driver: vmwgfx v: 2.14.0.0 bus ID: 00:02.0 
           chip ID: 15ad:0405 
           Display: x11 server: X.Org 1.19.6 driver: vmware unloaded: fbdev,modesetting,vesa 
           resolution: 1280x800~60Hz 
           OpenGL: renderer: SVGA3D; build v: 2.1 Mesa 18.2.8 direct render: Yes 
Audio:     Device-1: Intel 82801AA AC97 Audio vendor: Dell driver: snd_intel8x0 v: kernel 
           bus ID: 00:05.0 chip ID: 8086:2415 
           Sound Server: ALSA v: k4.15.0-20-generic 
Network:   Device-1: Intel 82540EM Gigabit Ethernet driver: e1000 v: 7.3.21-k8-NAPI port: d020 

Any ideas or recommendations? Thanks in advance

**Comment by jc1125** [comment] 2020-03-25 15:01
Same issue here. Not sure why. I double-checked the size and sha256sum of the .deb file and they match.

**Comment by jc1125** [comment] 2020-03-25 15:14
Not sure that it's the same problem, but if you read the issue below this one you will find that essentially the current version of the launcher has broken the package on linux. Looks like we just need to wait until 2.2.7 :c unless somebody has the .deb file for 2.2.5 or 2.2.4 laying around and can provide it.

**Comment by bunatl** [comment] 2020-03-25 15:27
@jc1125 well, shouldn't be that hard, since I assume they store all version releases here on github..

**Comment by MrCarroll** [comment] 2020-03-25 17:32
This is indirectly a duplicate of #110 and you should find there'll be a Flatpak package update in the next few hours that resolves this, now that Jagex has released a new launcher to the repository.

**Comment by bunatl** [comment] 2020-03-25 18:23
@MrCarroll It seems so. I read through the #110 and hope once the Flatpack will update this issue will be resolved. Anyway thanks for the time and point to the other issue. Now I know, I am not the only one!

**Closed** 2020-03-27 09:36 UTC
