### ISSUE TITLE
Runesacpe Launcher fails to download.

### ISSUE THREAD

**Issue by OMTDesign** [flathub/com.jagex.RuneScape#99] opened 2019-11-12 02:21 UTC
Hello,

While flatpack was in the middle installing runescape-launcher, at 9/12MB of its download, it failed.  I tried to reinstall the application many times, but then the launcher failed to download at all.

It seems Jagex has updated their launcher.
https://secure.runescape.com/m=news/news-post-linux-client-improvements

They must have deleted the file for the old launcher off their server.

```flatpak install flathub com.jagex.RuneScape
Looking for matches…

com.jagex.RuneScape permissions:
    ipc           network     pulseaudio     x11     devices
    tags [1]

    [1] proprietary


        ID                     Arch     Branch   Remote    Download
 1. [✗] com.jagex.RuneScape    x86_64   stable   flathub   9.3 MB / 12.9 MB

Error: While downloading https://content.runescape.com/downloads/ubuntu/pool/non-free/r/runescape-launcher/runescape-launcher_2.2.4_amd64.deb: Server returned status 404: Not Found
error: Failed to install com.jagex.RuneScape: While downloading https://content.runescape.com/downloads/ubuntu/pool/non-free/r/runescape-launcher/runescape-launcher_2.2.4_amd64.deb: Server returned status 404: Not Found
```

**Comment by Garbee** [comment] 2019-11-12 12:08
I'll take a look at this when I'm back home at a system I can run builds on. I have workarounds in the system so if they're updating the launcher then those could be impacted and cause a worse experience if the build is just updated to the new launcher without being checked over.

It will probably be Thursday morning when this is looked at.

**Comment by Tjzabel** [comment] 2019-11-12 22:25
@Garbee this is due to v2.2.5 that was released this past Monday. New flatpak downloads won't be able to be pulled until flathub is updated with the latest version.

**Comment by Tjzabel** [comment] 2019-11-12 22:29
Should be fixed by PR #98

**Comment by Garbee** [comment] 2019-11-13 09:52
I know what it is from yes, also fully aware of the consequences. I looked into it yesterday and confirmed it fixes the things I patched around. I'll get this done ASAP when I'm back home. It's more work than just fixing a hash and link.

**Comment by tristan957** [comment] 2019-11-14 03:14
@Garbee thank you for your work

**Comment by Garbee** [comment] 2019-11-14 04:04
There is a PR that was rushed together that seems to do what is needed already. I just need to actually run it and verify myself.

It is super late and I just had an agonizing day of travel, so that will be handled at some point tomorrow.

**Comment by OMTDesign** [comment] 2019-11-15 01:09
Thanks to all those that helped in this thread.
I can verify that the following build does work:
`flatpak install --user https://dl.flathub.org/build-repo/10806/com.jagex.RuneScape.flatpakref`

**Comment by Garbee** [comment] 2019-11-15 11:01
Until this gets merged later today, keeping the issue open for anyone else coming through about this issue right now.

**Comment by Garbee** [comment] 2019-11-15 19:47
Should be fixed now with the new build being live.

**Closed by Garbee** 2019-11-15 19:47 UTC
